services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: chirp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SVvo8AlXQDbD6xvZ
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d admin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=admin'
      - 'RABBITMQ_DEFAULT_USER=admin'
    ports:
      - '5672:5672'
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  chirp:
    image: 'chirp:latest'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - rabbitmq
      - redis
