CREATE SCHEMA IF NOT EXISTS user_service;

CREATE TABLE IF NOT EXISTS user_service.users
(
    id                 BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    external_id UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
    username           VARCHAR(255) NOT NULL UNIQUE,
    hashed_password    VARCHAR(255) NOT NULL,
    email              VARCHAR(255) NOT NULL UNIQUE,
    has_verified_email BOOLEAN      NOT NULL        DEFAULT FALSE,
    created_at         TIMESTAMP    NOT NULL        DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL        DEFAULT CURRENT_TIMESTAMP,
    version            BIGINT       NOT NULL        DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_users_email ON user_service.users (email);
CREATE INDEX IF NOT EXISTS idx_users_external_id ON user_service.users (external_id);
CREATE INDEX IF NOT EXISTS idx_users_username ON user_service.users (username);
