spring:
  application:
    name: chirp
    admin:
      enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/chirp
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    pool:
      initial-size: 5
      max-size: 10
      max-idle-time: 5m
      max-life-time: 20m
      max-acquire-time: 20s
    properties:
      connectTimeout: 30
      tcpKeepAlive: true
      prepareThreshold: 5
      preparedStatementCacheQueries: 256
      preparedStatementCacheSizeMiB: 5
  flyway:
    url: jdbc:postgresql://localhost:5432/chirp
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  show-actuator: true
